### ISSUE TITLE
v2 API endpoint

### ISSUE THREAD

**Issue by eliot-akira** [will-in-wi/letsencrypt-webfaction#106]
Hello,

First of all, thank you so much for providing this useful script. I'm using it regularly on many domains at WebFaction, and loving the automated issuing of certificates.

I learned that Let's Encrypt plans to release a [v2 API endpoint in January 2018](https://letsencrypt.org/2017/06/14/acme-v2-api.html). It supports wildcard certificates, among other improvements. From the article, it looks like the new version of API will use a different standard for interacting, that's not backward compatible.

Do you have any plans to support the new API when it's available? I imagine it's not a trivial change, so perhaps others who are using this script can contribute to the effort.

**Comment by will-in-wi** [comment]
Good question, and thanks for raising it!

This project depends on the acme-client gem to interact with Let's Encrypt's API. They have an issue for this here: https://github.com/unixcharles/acme-client/issues/126

At this point, I'm waiting for `Acme::Client` to support V2, and then I'll make any needed changes to this client to also support that.

As an aside, Webfaction has said in the past they intend to have first-party support for Let's Encrypt built in to the admin. I keep hoping they will finally get this out the door and I can archive this project. I'm not going to put much work in on this before January just in case they launch support before then and I don't have to bother. 😄 But if they still haven't done so at that point, I'll update this project to support V2.

I'm leaving this ticket open until V2 is supported.

**Comment by eliot-akira** [comment]
Wonderful, that open issue for acme-client looks optimistic, that supporting v2 is on the roadmap.

Perhaps I will "poke" at WebFaction's support forum, to see how the admin integration with Let's Encrypt is going.  I'll post back here if I learn anything.

**Comment by will-in-wi** [comment]
Note to self that the full release of the v2, wildcard supporting API endpoint is scheduled for Tuesday, February 27.

https://letsencrypt.org/2017/12/07/looking-forward-to-2018.html

**Comment by eliot-akira** [comment]
A post on the WebFaction forum indicates that they're [planning to support Let's Encrypt wildcard subdomains](https://community.webfaction.com/questions/21528/lets-encrypt-wildcard-subdomains-ssl-certificates).  "..it is the first priority in our roadmap after releasing it"

**Comment by will-in-wi** [comment]
Wildcard support is live! https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Interestingly enough:
> Additionally, wildcard domains must be validated using the DNS-01 challenge type. This means that you’ll need to modify DNS TXT records in order to demonstrate control over a domain for the purpose of obtaining a wildcard certificate.

This _should_ still be doable via the WebFaction API, but it certainly makes things trickier.

**Comment by sebleclerc** [comment]
Good news! `Acme::Client` v2 endpoint is now implemented: https://github.com/unixcharles/acme-client/issues/126

**Comment by vallieres** [comment]
Any update since (I think) all the building blocks are now available?

**Comment by will-in-wi** [comment]
No particular update… I've been really busy with changing jobs and my weekends have mostly been taken up with higher priority personal stuff. So I haven't had much time to code.

My highest priority with this project is https://github.com/will-in-wi/letsencrypt-webfaction/issues/122 and resolving it with a much more user friendly v3: https://github.com/will-in-wi/letsencrypt-webfaction/pull/125

Once that is done and out, I'll probably start work on updating the code to use the v2 of `Acme::Client`. This will likely get released initially without wildcard cert support.

Supporting wildcard certs requires DNS validation. I've been doing HTTP validation thus far, so that adds a layer of complexity. WF has the APIs to create the necessary TXT records, so it should be possible to do. However, it'll probably take a lot longer to validate, as the TXT settings don't apply immediately. It might involve either letting the process run a lot longer (10s of minutes?), or introducing some kind of storage so that the process runs every couple of minutes to check on whether validation finished. Either way, this is a lot of work. I want to do it, but it'll take a while. Also, I know WF is working on first-party LE support, and once they (finally) release that, all of this work will become moot, so I'm struggling with how much effort to put into a major feature like this when it'll hopefully become pointless fairly quickly.

Maybe not the update you were hoping for, but that's the status of the project as of right now.

**Comment by abudarevsky** [comment]
Hi,

So, finally, WF has announced it's own LE client but without wildcards support. Is there any chance you might do it?

**Comment by will-in-wi** [comment]
Not sure yet, but probably not. My plan is to switch all of my websites over to the new control panel certs, and if that goes well, add a big message to the top of the readme that this utility will just get bugfixes in future.

**Comment by will-in-wi** [comment]
Looks like Let's Encrypt turned off ACMEv1 support, so this plugin is broken unless it gets upgraded, per https://github.com/will-in-wi/letsencrypt-webfaction/issues/162

**Comment by will-in-wi** [comment]
I should say, to be clear, I'm looking at upgrading to `Acme::Client` v2 and supporting this, but I might not. This utility has effectively been replaced by what WebFaction can do built-in now, and I am not using this utility myself anymore. I'll try to make a clear decision and archive this repo if I decide to not support it anymore, or release v2 support if I do.

If someone wants to tackle the upgrade, I'd accept a PR and publish a new version. Please post if you give it a shot so that we don't have duplicated efforts.

**Comment by jasonsultana** [comment]
"Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail." (Let's Encrypt)

Is there any plan to upgrade this to ACME v2 before June?

**Comment by will-in-wi** [comment]
Hey folks, thank you so much for your interest in this tool! I've just pushed version 4.0.0 which supports ACMEv2. This requires changing from `endpoint` to `directory` in your config file, which is detailed in [the upgrading docs](https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/docs/upgrading.md). Please let me know if you encounter any issues!

**Comment by will-in-wi** [comment]
I should add, please report any issues in new tickets, not in this thread. Thanks!
