### ISSUE TITLE
Using django-letsencrypt

### ISSUE THREAD

**Issue by javierdaza** [will-in-wi/letsencrypt-webfaction#107]
Hi there,

Maybe this question is os out of topic but i hope you can help me. I plan on using this [django-letsencrypt](https://github.com/urda/django-letsencrypt) but the `ACME Challenge` must be generated manually. _Do you know if I can do that with **letsencrypt-webfaction**?_ 
Thank you for your understanding

**Comment by will-in-wi** [comment]
Good question.

I don't think django-letsencrypt overlaps at all with letsencrypt-webfaction. It seems to handle serving the challenge files, and that's about it (if I'm reading the docs correctly).

Letsencrypt-webfaction handles this part of the puzzle by dropping a file onto the disk somewhere. The major heavy lifting is interacting with WebFaction's API, which is required to use TLS on their shared hosting.

Hypothetically, you could have letsencrypt-webfaction interact with the django-letsencrypt app so that the former generates the challenge, the latter serves it, and then the former gets the cert and key and installs them in the webfaction admin. However, at that point, you might as well just use a python library for the rest of the Let's Encrypt integration and rewrite what letsencrypt-webfaction is doing already. Either way, this is probably out of scope for this project.

Does this answer your question?

Some other possible help for using Django can be found here: https://github.com/will-in-wi/letsencrypt-webfaction/wiki/Django
