### ISSUE TITLE
"Failed to verify statuses"

### ISSUE THREAD

**Issue by trilobutt** [will-in-wi/letsencrypt-webfaction#112]
Hi, 
Thank you very much for creating this tool! 
I followed the instructions, but when I get to the last step of running the letsencrypt_webfaction command, it  gives me the following:

```
Failed to verify statuses.
xxxxxxx.com: Invalid response from http://xxxxxx.com/.well-known/acme-challenge/xxxx: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p"
Make sure that you can access http://xxxxxx.com/.well-known/acme-challenge/xxxxx
```
I can see the .well-known/acme-challenge folder in my SFTP client, and I can go directly to the link without getting a 404 error.

Any idea where the error might be? I've checked all the parameters and they are definitely correct. I am running a Wordpress application.

Thank you!

**Comment by will-in-wi** [comment]
I'd double-check your htaccess file. Also confirm that the file is accessible over http, not just https. Let's Encrypt hits the http version when validating, although it will follow a redirect to https. You can grab the URL out of the error message and use that in testing. Make sure hitting that from your browser or cURL works before running the script again, just so you don't hit api limits.

Since this stuff is usually specific to your setup, you could open a ticket with WebFaction asking them why the particular URL is forbidden.

**Comment by trilobutt** [comment]
So I can open the http version in my browser, but running it in SSH like this:
`curl -v http://www.orangereel.com/.well-known/acmechallenge/OrIZZ6aDBL9vQaoJJcF9a7lGCkeeugLj49CADkJBJuk
`
gives a 403 Forbidden error.

I will open a ticket with Webfaction then, I can't figure out where the error might come from. Thanks!

**Comment by will-in-wi** [comment]
Sounds good. I'll be curious to find out what WebFaction says.

**Comment by will-in-wi** [comment]
You have three instances of `RewriteRule .* - [F,L]` prepended by rewrite conditions. One of those is probably the issue. I'd suggest placing them back one at a time and seeing if you can drill down into which one makes that file inaccessible.
