### ISSUE TITLE
output_dir ignored; certs appear in ~/certificates/...

### ISSUE THREAD

**Issue by mhulse** [will-in-wi/letsencrypt-webfaction#118]
My config file has this:

```text
output_dir: '~/le_certs/'
```

But my certs show up in `~/certificates/`.

When running `--help` I see:

```text
--output_dir=OUTPUT_DIR      Location on the filesystem to which the certs will be saved.
```

Not sure if you want to update the help/docs to clarify? I assume this is now the expected behavior.

Thanks for the useful tool!

**Comment by will-in-wi** [comment]
Good catch! I'm not sure how I missed that. In the 1.x releases, we dropped the certs into a folder and then told WebFaction where to pick them up. as of 2.0, we send the certs directly to the WebFaction API, and they place it in `~/certificates` (which is root-owned). So this param is no longer used or needed. I've removed it from the codebase and it will be fixed in the next release.

Thanks!

**Comment by mhulse** [comment]
Thanks so much for the quick reply and update!

This code has been a life saver!!!
