### ISSUE TITLE
Upgrading strictly necessary?

### ISSUE THREAD

**Issue by ElectricFeet** [will-in-wi/letsencrypt-webfaction#137]
Hi Will! I’ve been watching the latest release with interest (and thanks!) and I will upgrade eventually. However a question arises: If I have a working installation, running on Cron, with no issues, is there a compelling need to upgrade? Am I heading towards some sort of brick wall at some point?

**Comment by will-in-wi** [comment]
Is the upgrade "strictly necessary"? No. Your instance on an older version should continue working for quite a while yet.

A couple of reasons to upgrade to v3 (in no particular order):
1. It fixes a bug where it registered every time with LE using a new certificate. Turns out that LE expects a single client to store and reuse the registration certificate. There are registrations per IP limits, and, on some servers, enough people are using <=v2 to cause each other to hit the limit. There is kind of a "good server citizen" benefit to upgrading, especially on those servers.
2. It'll (hopefully) make adding or modifying certificates easier. Since you just have to edit a config file instead of adding a complicated Cron entry, this should be a lot easier.
3. It'll check for remaining certificate lifespan each time it is run and only renew when needed. This should make it a lot easier to time renewals.
4. New features will show up on v3. The main one I'm hoping to release is LE API v2 support with wildcards. Not done yet, and no idea when it'll be done, but when it does, it'll be on v3.

If none of these matter much to you now, there isn't a good reason to upgrade. 😄

A good reason not to upgrade is that I'm still hoping WF will release first-party support at some point soon (they've been promising this for quite a while now), at which point you'll want to rework everything using that anyway. 😄

This answer your questions?

**Comment by ElectricFeet** [comment]
Absolutely it answers my questions :-)

“Good server citizen”, Is probably the most compelling reason in my case

I too am waiting on WebFaction, sigh. (Though since learning that they are now GoDaddy and sharing data with GoDaddy I’m having some second thoughts on WebFaction...)

Thanks for an excellent response, as ever :-)
