### ISSUE TITLE
SMTP Instead of Sendmail

### ISSUE THREAD

**Issue by mojowen** [will-in-wi/letsencrypt-webfaction#14]
Having issues with Sendmail:

````
sendmail: authentication failed (method CRAM-MD5)
sendmail: server message: 535 5.7.0 Error: authentication failed: authentication failure
sendmail: could not send mail (account default from dummy)
sendmail: authentication failed (method CRAM-MD5)
sendmail: server message: 535 5.7.0 Error: authentication failed: authentication failure
sendmail: could not send mail (account default from dummy)
````

I think they may have changed some of the settings - and have attempted to get [Pony to use SMTP instead](https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/emailer.rb).

May be worth adding a flag to point to a configuration file or something that Pony would use when specified (Although I'm also having issues with using Webfactions' SMTP too).

**Comment by will-in-wi** [comment]
Could you run `echo "Subject: Test Email" | sendmail youremail@example.com` and verify that it isn't coming through?

I just tried that command on a CentOS 6 server and it worked for me.

My guess is that WebFaction has Sendmail configured to use their SMTP servers, and they are breaking in some way. If the above command doesn't work for you, could you open a ticket with WebFaction to resolve that?

I'm trying to stick with Sendmail for the moment because it is really easy for people to set up and Webfaction is supposed to support it. It might be worth adding support for Pony configuration at some point…

**Comment by mojowen** [comment]
I think there's something up with this particular account - I just tried your test from a different webfaction account and it worked fine.

Thanks for your help!

**Comment by will-in-wi** [comment]
My pleasure!

**Comment by will-in-wi** [comment]
I've added a note about this to the troubleshooting section of the wiki.
