### ISSUE TITLE
Multiple emails

### ISSUE THREAD

**Issue by jimmitt** [will-in-wi/letsencrypt-webfaction#140]
Hello, I use different email addresses for different domains.  Your example has a single letsencrypt_account_email at the top and looking through the readme and wiki I do not see any information about setting emails.  Is it possible to use a different email for each domain?

**Comment by jimmitt** [comment]
I was asking about different Let's Encrypt registration email addresses.  I use a different email for administration of each of my sites and prefer to keep them separate.  It looks like Let's Encrypt does not put an email in the certificate and only uses them for reminders.  If that's the case, it's not necessary for me, however, I could see this being used if someone was registering on behalf of clients or perhaps for a team versus a single webmaster.

**Comment by nootrope** [comment]
FWIW, I use different cert registration addresses for each of the websites I host on my account because they're friends' sites and I'd rather they get LE notifications instead of me.

I use a --config argument on the crontab entry for each renewal command. It points to a YAML file elsewhere on the server. @will-in-wi does `letsencrypt_webfaction` not support that cli parameter anymore?

**Comment by will-in-wi** [comment]
It sounds like this is a more common use case than I thought, which is great to know! I'll take a look at it and see how tricky it is to do. Otherwise, I'll get the config file param working, and that'll serve as a workaround.

**Comment by will-in-wi** [comment]
I'm still looking into this, but thought I'd mention that once the `--config` support comes out (#136), there may be a new issue where every config file instance is sharing the one global private registration key. I'm not sure how LE would handle multiple email registrations with the same private key, but I'm guessing that if they aren't blocking that, it's just an oversight on their part. I'll need to add the ability to also define a custom private registration key for this to work.

**Comment by nootrope** [comment]
Am I understanding correctly that the v2 implementation of a `--config` cli argument resulted in the global private key being used to generate certs for the other config files in my Webfaction account?

**Comment by will-in-wi** [comment]
It's kind of complicated, but the short answer is: no, that is not the case.

Keys are used for two different things in Let's Encrypt:
1. User registration
2. Certificate creation

You are probably familiar with (2), where each time you want a cert, you generate a certificate request using a private key, and Let's Encrypt issues a signed cert using that certificate request. It is best practice to rotate private keys and not reuse them between certs (or even between renewals). This utility has always generated a new private key every time it issued or renewed a certificate.

The issue that was fixed in v3 was how (1) was handled. Let's Encrypt requires that a special private key (which must be different from your cert private key) be issued and associated with your email address. This is the "registration" part of the cert issuance process. In v1 and v2, every time a cert was issued, a new private key was generated and registered. This was incorrect, and caused issues (https://github.com/will-in-wi/letsencrypt-webfaction/issues/122). The correct behavior (which is implemented in v3) is to issue one private registration key per email address and reuse going forward.

The issue now is that this utility doesn't support having multiple _registration_ private keys, which is most likely required in order to have multiple config files and multiple registration email addresses.

**Comment by nootrope** [comment]
Thanks for explaining the fine points. I imagine the same complication currently arises with a single config file containing multiple LE user registrations, each under its own `[[certificate]]` header?

**Comment by will-in-wi** [comment]
😄 The multiple usages of the term "keys" might be adding to the confusion. In the template comment you quoted, I'm referencing configuration keys, not private keys. Does this make sense?

Reiterating for clarity, multiple certificates on one account are supposed to share a _registration_ private key, just not a SSL cert private key.

One thought I just had is that when WebFaction finally releases their built-in Let's Encrypt support, it would surprise me if they supported multiple custom registration email addresses. They may even use an email address and LE registration private key that is specific to their main global account, instead of being per-customer. So if I support this, it may be causing users like you to depend on something that will likely go away at some point in the future anyway…

Does this make sense, and what do you think?

**Comment by nootrope** [comment]
> I'm referencing configuration keys, not private keys. Does this make sense?

Hah! Yeah, I did get confused and thought the "...All the same keys..." phrase was referring to the registration and TLS/SSL private keys. Thanks for clarifying that you meant TOML keys.

Can't speak for other fans of letsencrypt_webfaction, but, I appreciate and use your tool because it is convenient, educative, and prevents me from having to build one. ;-) If I don't like Webfaction's forthcoming tool, I might build my own from certbot and/or continue to use yours or a fork of it, if it's still around, even if no longer supported by you. If or when you add support for multiple LE account registration keys, I will welcome it and I'm sure so will others, but I realize that you have a life to live and wouldn't take that eventuality for granted. Grateful for your hard work!

**Comment by htrex** [comment]
> One thought I just had is that when WebFaction finally releases their built-in Let's Encrypt support, it would surprise me if they supported multiple custom registration email addresses.
It's some years that WebFaction answers "NO ETA" for the "We are working on it" built-in Let's Encrypt support. I'm confident they'll support multiple emails and worried that email will be obsolete by the time they release it! ;)
In the meantime, thank you @will-in-wi !

**Comment by will-in-wi** [comment]
I'm going to close this I understand what people are looking for here, but I don't think WebFaction is going to support this anytime soon. They have now officially released first-party LE support, so most use cases should switch over to them. If you can't switch over to them for some reason, file a ticket with them, and comment here: https://github.com/will-in-wi/letsencrypt-webfaction/issues/160
