### ISSUE TITLE
Ability to configure location of letsencrypt_webfaction.toml

### ISSUE THREAD

**Issue by paulrobertlloyd** [will-in-wi/letsencrypt-webfaction#156]
Hi William,

Just upgraded to the latest version from v2; a great project just got even better! Thanks for your continued support of this project. I _really_ like the new configuration format; far fewer files to manage -- the ability to configure multiple domains and paths for a certificate has also addressed a pain point I had with the previous version.

Just one feature request. Would it be possible to choose a location for the configuration file, perhaps as part of the `init` command? I like to keep my user folder clean, and save configuration files in the same location. An alternative suggestion would be to save `letsencrypt_webfaction.toml` within the `.config/letsencrypt_webfaction/` folder.

Thanks again,

Paul

**Comment by will-in-wi** [comment]
You can pass `--config mypath/myconfig.toml` to the run command to have a custom config file. I'll probably leave the init command as is, since it is easy to move the config file. Does this work for you?

**Comment by paulrobertlloyd** [comment]
A-ha, no that’s perfect! I didn't see the `--config` option in the documentation, did I miss it, or does it need adding?

**Comment by will-in-wi** [comment]
I don't think it's anywhere in the docs, unless it's part of running `letsencrypt_webfaction run --help` which I'm not sure works, and I don't see documented anywhere if it does. Quite poorly documented, regardless.

If you have time, feel free to open a pull request with some docs! Otherwise, I'll keep this ticket open to remind me to do so.

WebFaction is rolling out their official LetsEncrypt support on Monday, FYI. That'll probably be easier to use than this ever could be.

**Comment by paulrobertlloyd** [comment]
I have created #157 as a first attempt at including this info in the docs. Feel free to edit/change if its not quite right. `--help` does work, FYI.

Interesting to see that native support for LetsEncrypt is finally being supported. Will certainly be interested to compare with this tool. Thanks again!
