### ISSUE TITLE
Account creation on ACMEv1 is disabled

### ISSUE THREAD

**Issue by vegemite4me** [will-in-wi/letsencrypt-webfaction#162]
Renewing certificates is usually a breeze, but unfortunately tonight I was presented with the following error message:

> /home/myuser/.letsencrypt_webfaction/gems/gems/acme-client-1.0.0/lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!': Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details. (Acme::Client::Error::Unauthorized)

I am using version 3.2.0 of letsencrypt_webfaction.

Can anyone tell me what I need to do (with regards to continuing to use letsencrypt_webfaction) to get past this?

Thank you

**Comment by will-in-wi** [comment]
Thanks, I hadn't seen this. I haven't done any work on supporting ACME v2, mostly due to my migrating everything over to WebFaction's first-party Let's Encrypt support, and starting to migrate personal stuff off of WebFaction the the wake of their GoDaddy acquisition.

I'm going to close this ticket and track this issue in the preexisting issue https://github.com/will-in-wi/letsencrypt-webfaction/issues/162

**Comment by vegemite4me** [comment]
This error gave me a reason to properly investigate WebFaction's LE support, and I have now set that up for all my domains. So I am no longer blocked by this.

Thank you so much for creating this and all the work you put into it. It is a great piece of software.

**Comment by will-in-wi** [comment]
I'm glad to hear you got it working! And thank you for the kind words. I think my favorite part about building and maintaining this utility was the community. Everyone who has filed bugs, asked questions, or generally interacted with me has been wonderful.
