### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by mchatzikos** [will-in-wi/letsencrypt-webfaction#163]
Hello,

I am getting an error with v3.2.0.

I created the config file with the init command, and configured it.  But when I try to use the certificate what I get is this:

```
$ letsencrypt_webfaction run --config /home/myapp/.letsencrypt_webfaction/config/le_private.toml
/usr/local/lib/ruby22/ruby/2.2.0/xmlrpc/client.rb:271:in 'call': Not allowed to login to machine "myserver.org" (XMLRPC::FaultException)
        from /home/myapp/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/webfaction_api_credentials.rb:38:in 'session_id'
        from /home/myapp/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/webfaction_api_credentials.rb:24:in 'valid?'
        from /home/myapp/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/lib/letsencrypt_webfaction/application/run.rb:28:in 'run!'
        from /home/myapp/.letsencrypt_webfaction/gems/gems/letsencrypt_webfaction-3.2.0/exe/letsencrypt_webfaction:7:in '<top (required)>'
        from /home/myapp/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in 'load'
        from /home/myapp/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction:23:in '<main>'
```

I cannot understand what the problem is.  The username and password are the same as what I use to log in to my.webfaction.com.

Please let me know how to proceed.

Thanks,
Marios

**Comment by will-in-wi** [comment]
I'd probably need to ask for your config file in order to figure this out, but I'm starting to wind this down, since you are going to run into https://github.com/will-in-wi/letsencrypt-webfaction/issues/106#issuecomment-562378734 even if you get it working. I have migrated everything I use to WebFaction's first-party Let's Encrypt support, and am migrating a lot of my sites off of WebFaction entirely, since their acquisition by GoDaddy.

**Comment by mchatzikos** [comment]
Ended up configuring it through the control panel.
Thanks for your help!
