### ISSUE TITLE
renewal only if impending expiration

### ISSUE THREAD

**Issue by npdoty** [will-in-wi/letsencrypt-webfaction#18]
Rather than choosing the renewal rate via the regularity of a cron job, it might be nice to take advantage of `certbot` functionality that renews a cert if and only if it's within one month of expiration.
https://certbot.eff.org/docs/using.html#renewal

That way, we could set the cron job to run daily or weekly and it would just actually create a new certificate whenever one was needed.

**Comment by npdoty** [comment]
Maybe I'm just misunderstanding the documentation. The suggested crontab runs every day every other month, so either this renewal issue is already handled (although I don't see that in my testing) or the cron job will run unnecessarily often, bothering the ISP support and breaking the Let's Encrypt rate limit.

**Comment by will-in-wi** [comment]
Valid question.

The short answer is that I took the easy route by simply saying to renew the cert every other month so you never risk going over the three month expiration date.

There used to be a bug in the docs which made the crontab run every other day on odd months. This was wrong and has since been corrected: http://crontab.guru/#0_4_1_*/2_*

I was reading certbot docs just the other day and noticed how they suggest running it twice a day and having it check the expiration time. This is a great idea, I'm just not sure whether it is worth the extra 100-200 lines of code or so to track state of the previous issued cert so that it knows whether to issue a new one or not.

Since certbot issues a new cert within a month of renewal, it is essentially renewing every 2 months, just like this tool, albeit in a much more clever manner.

Per rate limits, [LE docs](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769) give you 20 certs per second level domain per week. So if you have >20 certs for *.example.com, you will need to modify the crontab to spread out cert renewal across multiple weeks or even multiple months.

Per bothering the support guys (who do an absolutely awesome job in my experience), I am guessing that they will eventually either offer an official API for cert installation, or they will integrate LE into their control panel, or both. Until then, this script simply demonstrates demand for such a tool. I do suggest that people not exactly use the suggested crontab, otherwise the WF guys will get swamped every other month on the same day with a huge pile of cert installation requests.

Does this address your question? Thanks for using this tool! I hope you find it helpful.

**Comment by npdoty** [comment]
Ah, just a bad link in the README.md that threw me off.

I was thinking that if this script could run `certbot` itself, then certbot would handle the logic of checking whether the certificate was about to expire or not. But I agree that it's not worth re-writing all that code for this project. I believe you're right that eventually WebFaction will just integrate this automatically.

And yes, I'm finding this tool very helpful! Many thanks.

**Comment by will-in-wi** [comment]
Having the script run certbot itself would probably have been the long term better approach. Honestly, I just wanted to muck around with implementing my own client to solve this problem, and ended up publishing it and trying to make it more broadly useful.

Thanks again for fixing the docs!
