### ISSUE TITLE
Elaborate instructions for Email configuration and Cron

### ISSUE THREAD

**Issue by SNaushadS** [will-in-wi/letsencrypt-webfaction#32]
Thanks for the script. it has helped me a lot.

I am Designer, and i just understand code at the high level.
Can easily follow instructions and i am aware of how to execute CLI commands.

For a user like me, it will be helpful if the documentation has some more steps mentioned.

For example.
I receive the following error when executing the command:

`sendmail: recipient address support@webfaction.com not accepted by the server
sendmail: server message: 554 5.7.1 <MYGMAILADDRESS@GMAIL.COM>: Sender address rejected: Please use Gmail's SMTP servers
sendmail: could not send mail (account default from dummy)
sendmail: recipient address MYGMAILADDRESS@GMAIL.COM not accepted by the server
sendmail: server message: 554 5.7.1 <MYGMAILADDRESS@GMAIL.COM>: Sender address rejected: Please use Gmail's SMTP servers
sendmail: could not send mail (account default from dummy)
`

I know its regarding server unable to use Gmail to send email (to me and webfaction) and you have already found a solution towards it mentioned here [https://github.com/will-in-wi/letsencrypt-webfaction#custom-email-configuration](url)

Doesn't help much to me as a Designer. 

What would help : 

1. Where to find this file OR is it to be created new
2. Where to save this file.
3. Some more clear instructions on how to use the cron.

You may decide to keep this script as dev oriented, However, a little more documentation will open it to more users.

My Setup:
All WordPress sites.

Thanks.

**Comment by will-in-wi** [comment]
Thanks for your comments! I'm also working on some documentation improvements in https://github.com/will-in-wi/letsencrypt-webfaction/issues/30 as well.

The trouble with step by step directions is that there is such a diversity of application setup that there is no one way to do it. Honestly, if there was one way to do it, I would have automated the steps so that you wouldn't need them. I'll keep trying to find ways to simplify. I hope that the WebFaction developers roll this type of thing into their own control panel so that scripts like mine become obsolete. That would provide a much better user experience for non-developers.

Per your specific points:

> Where to find this file OR is it to be created new
> Where to save this file.

I'll make a note to say that a good default place for this file is your home directory. You do need to create it yourself.

> Some more clear instructions on how to use the cron.

That's being addressed in https://github.com/will-in-wi/letsencrypt-webfaction/issues/30

Thanks again!

**Comment by will-in-wi** [comment]
The specific gmail documentation improvement is being tracked in https://github.com/will-in-wi/letsencrypt-webfaction/issues/33 now.

Closing.

**Comment by SNaushadS** [comment]
Thanks for the clarifications. Yes, hoping that WF will have similar stuff in their control panel, but they don't have an ETA yet.
