### ISSUE TITLE
What am I missing? No ~/le_certs

### ISSUE THREAD

**Issue by simondrabble** [will-in-wi/letsencrypt-webfaction#56]
I'm not sure what step I've missed but upon (presumably) successful run of letsencrypt_webfaction I get neither a ~/le_certs directory nor any sort of confirmation email. The relevant .well-known directory IS created inside my web app, and I can reach the generated keys via http just fine. The command completes silently, which I am taking to mean success.

Also, I have seen mention of a --support_email parameter to the command but that gets rejected. 

I'm using version 2.0.0 of letsencrypt_webfaction. The described behaviour occurs both for production and when fired against the staging server.

**Comment by will-in-wi** [comment]
2.0.0 changed quite a bit. In the 1.x series, this utility sent an email to WebFaction asking them to install the cert. Since then, WebFaction released an API for automatically installing a certificate. The 2.x series takes advantage of this API to automatically install the certificate. Thus, the `--support_email` param no longer exists, and since the cert is uploaded right into the admin, it isn't stored on disk.

If you see something in the readme that is misleading in this regard, please let me know. I just released 2.0.0 yesterday and very easily may have missed something.

Thanks!

**Comment by will-in-wi** [comment]
I just searched the readme for `le_certs` and found a spot I missed. I just committed a fix to clean that up. https://github.com/will-in-wi/letsencrypt-webfaction/commit/83852656200fbe4b55f0811066fb9205c12cda55

**Comment by simondrabble** [comment]
Thanks @will-in-wi  for the quick response! I had no idea I was on such the bleeding edge, but I'll look for the cert to verify.. and there it is!

**Comment by simondrabble** [comment]
And I realise this is probably outside of the scope of letsencrypt_webfaction, but firefox now reports:

The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported.

for my website. Any pointers on how to fix?

**Comment by will-in-wi** [comment]
I'm glad to hear it works for you! Hopefully, 2.0.0 is ready to be used by everyone, but, as with all major changes, it is possible that I missed something. Thanks for reporting the readme issue. If you see any other bugs or documentation issues, please file more tickets!
