### ISSUE TITLE
How long does it take for new certificate to be activated

### ISSUE THREAD

**Issue by panzerdp** [will-in-wi/letsencrypt-webfaction#57]
Hello William,

Some of my certificates soon expire, so I need to update them.

I updated letsencrypt_webfaction gem to latest 2.0.0 version. And used the new command that requires auth. on Webfaction API to install certificates automatically. The command worked fine, without errors.

The question is how much time does it take for the certificate to be activated? It passed a few hours, but my site still uses the old certificate.

Thank you.

**Comment by panzerdp** [comment]
PATH=$PATH:$GEM_HOME/bin GEM_HOME=$HOME/.letsencrypt_webfaction/gems RUBYLIB=$GEM_HOME/lib ruby2.2 $HOME/.letsencrypt_webfaction/gems/bin/letsencrypt_webfaction --letsencrypt_account_email dmitri@rainsoft.io --domains rainsoft.io,www.rainsoft.io --public $HOME/webapps/rainsoft_blog/ghost/core --username myusername --password *******
It seems like executing the command has no effect. No new certificates, no errors. 
Interesting what could be the problem.

**Comment by will-in-wi** [comment]
It might be that the certificate was created and installed, but not associated with your website. Check the Domains/Websites -> SSL Certificates section of the control panel to see if you can find your cert. If you can, go to Domains/Websites -> Websites, select your website, and in the Security section, select the cert from the dropdown.

**Comment by panzerdp** [comment]
You're right @will-in-wi! Thanks for the quick response.
I selected the new certificate, and now it works fine.

The last time I generated a certificate manually selection wasn't required. Probably because Webfacation support was doing that.

Thanks!

**Comment by will-in-wi** [comment]
Yeah, this is a new step. In future, letsencrypt_webfaction should update the certificate you selected instead of creating a new one. So selecting it should be a one-time step.

**Comment by pieplu** [comment]
@will-in-wi I have a question near that problem.
- I created a new certificate with verision 2 (thanks a lot for this new version)
- I set a cronjob to update the certificate
- I used the default value for 'cert_name' (no value ^^)

My certificat on webfaction admin will be updated, or letsencrypt_webfaction create a new one? (because I don't specify the cert_name).

**Comment by will-in-wi** [comment]
If you don't specify the cert name, the name will be automatically set to the first domain name with the dots replaced by underscores. So if you have a cert for `example.com,www.example.com`, the name of the cert will be `example_com`.

https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/args_parser.rb#L130

If you have any issues, please open a new ticket so that I can track it more easily.

Thanks!

**Comment by pieplu** [comment]
Thanks!
