### ISSUE TITLE
Checking webfaction API credentials before everything else ?

### ISSUE THREAD

**Issue by pakal** [will-in-wi/letsencrypt-webfaction#62]
Well I played with the script, and it kepts making login errors againts webfaction API, and just when I had fixed the issue (a typo in credentials), a new message appeared : "Error creating new cert :: Too many certificates already issued for exact set of domain"

I guess I have to wait 7 days, if the certificate hasn't been stored somewhere on server ?

Anyway, it'd be better for letsencrypt noobs like me, if issued certificates could be manually recovered when application fails uploading to webfaction (or else, check xmlrpc before doing the actual cert issuing).

**Comment by will-in-wi** [comment]
The cert isn't stored anywhere except by uploading it to the API. This is why I suggest using the staging server while getting this set up: https://github.com/will-in-wi/letsencrypt-webfaction#testing

However, your suggestion is a really good one. It would make a lot more sense to at least check the credentials before starting, since we want to fail before issuing the cert in that case. I'll look into that...

**Comment by dreamerworks** [comment]
+1
Same issue with credentials, and same too many certificates.

Extra information that led to the error:
To solve the problem of `LoginError (XMLRPC::FaultException)` I had to add:
`servername: 'WebXXX'`
on my config.yml.

Maybe there is a way to guess the servername and not require it to be on config.yml. Or, maybe explain this on the readme of this GitHub. 

I am very grateful for this tool, and hope you manage to integrate it further, as now Webfaction does not require the email to be sent to their staff. They have "thing" to add certs on my.webfaction... if we could just use that after the certificate is created instead of sending the email. 

Thanks

**Comment by ramirovaz** [comment]
I had `LoginError (XMLRPC::FaultException)` and it was useful first of all check a simple api request https://docs.webfaction.com/xmlrpc-api/tutorial.html , then i tried again and all works fine.

**Comment by will-in-wi** [comment]
@dreamerworks: Version 2.0 of this utility does use the new Webfaction Certificate API instead of sending the email.

Also, it does autodetect the host name, so I'm confused that it didn't work: https://github.com/will-in-wi/letsencrypt-webfaction/blob/master/lib/letsencrypt_webfaction/args_parser.rb#L125

**Comment by ramirovaz** [comment]
I had `LoginError (XMLRPC::FaultException)` and i thought it  was servername in config.yml. But then i tried to do a simple request to webfaction api, and i found that problem was password. For that, do a simple api request to webfaction api, helps.

**Comment by dreamerworks** [comment]
@will-in-wi Thaks for letting me know.
I didn't knew that, you did great in adapting to API instead of the emails.  

It's also a good to know that you have implemented autodetection of hostname, it just seemed that the config.yml started to work after adding the servername. I was wrong again, I removed it from my config file and the certificate generation worked well. 

It seems all my problems where due the change from command line arguments to config.yml arguments, it hurts to admit such a basic mistake, but I had an error in the user/pass of the config file. 
Thank you for spending time looking into this.

**Comment by will-in-wi** [comment]
I have 3-4 different WebFaction accounts and I'm sure I've mixed up the username/password at least once on each of them. :) I'm glad it worked for you!

**Comment by will-in-wi** [comment]
I've just pushed v2.0.1 which now checks your credentials before issuing the certificate. Hopefully, this will help others.

**Comment by pakal** [comment]
Awesome, thanks a lot  B-)
