### ISSUE TITLE
Plain text storage of password in config file is not best practice

### ISSUE THREAD

**Issue by hgezim** [will-in-wi/letsencrypt-webfaction#64]
`It is better to place this in a config file than to put it in the command line.`

Is there something I'm missing or are you suggesting I store my Webfaction password as plaintext on the server?!

**Comment by will-in-wi** [comment]
Yup. Think of what else is stored in plain text on the server. MySQL passwords, application passwords, etc. If someone can read files on your server, they have access to everything anyway.

If you have a suggestion as to how I can handle this (and encryption doesn't count, since the key would be stored alongside it), I'm all ears.

**Comment by hgezim** [comment]
I don't intend to use it as a cron job. I can a command once every 2 months.

Do you not want to consider this use case at all?

**Comment by will-in-wi** [comment]
I try to not pass judgement on people's use cases, as I don't know everything and can't possibly know about everyone's situation. I'd certainly consider a pull request.

However, I'm not going to write this code myself, and if it were a significant amount of additional code maintenance overhead, I wouldn't merge a PR.

My reasoning is that Let's Encrypt, for better or worse (and I've argued with them about this), has decided that they are only targeting situations where certificate renewal is fully automated. This is why they limited their cert expiration to three months. They have gone out of their way to say that if you want manual renewal for any reason, go elsewhere.

https://community.letsencrypt.org/t/maximum-and-minimum-certificate-lifetimes/264

I don't really want to be part of this fight. Whether you disagree or agree with this philosophy, they've made their stance clear, and this utility is going to stick with those guidelines as much as possible, to avoid unintended consequences.

In your case, I'd encourage you to either use Let's Encrypt within those parameters, or use something like StartSSL which will only require an annual manual renewal.

If your particular issue is the plain-text storage of the password, I'm happy to discuss options as it really is sub-par. But I can't come up with an option that isn't so easily defeatable as to be counter-productive. It'd be nice if WebFaction had app-specific API keys or something.

Does this make sense? It's about 10pm in my time zone, so I might be tired and unclear. Thanks for caring about this enough to open the tickets! I'll re-open for discussion.

**Comment by smallsaucepan** [comment]
The root of this problem is that the Webfaction API login options are pretty crummy. In a more sophisticated API we could use the control panel to create a long lived application key, perhaps limited to a certain subset of API functions, and pass that instead of the username and password.

Even if someone got hold of that key, they couldn't use it to call other API functions e.g. delete_app or create_user. Keys could be revoked, etc. Have posed the question to Webfaction. Will see what they say ...

**Comment by will-in-wi** [comment]
I'll be really curious to find out what they say. You are absolutely right about the risks, and I'd like to see a more easily revocable and focused API key of some kind.

**Comment by smallsaucepan** [comment]
For reference: [Fine grained API access to avoid plain text password storage](https://community.webfaction.com/questions/20578/fine-grained-api-access-to-avoid-plain-text-password-storage)

**Comment by will-in-wi** [comment]
I'm closing this ticket pending improvements from WebFaction for their API. Feel free to open a new ticket and reference this one if they make any such improvements.

Thanks!
