### ISSUE TITLE
No output on success?

### ISSUE THREAD

**Issue by radixdiaboli** [will-in-wi/letsencrypt-webfaction#86]
In the instructions, it offers this command as an example:

letsencrypt_webfaction --letsencrypt_account_email <email-address> --domains <domain[,domain[,domain...]]> --public <server-folder> --username <webfaction-username> --password <webfaction-password>

When I use this, and also the version for using the test server, no output is displayed on the commandline.  It would be nice if there was some indication of success.

Bonus request: It would also be nice if there was information in the "success" output about what to do next / how long it might take before certs become active.  This would be helpful in cases where perhaps the certification through this gem is successful, but was not set up correctly.  Then I would be able to distinguish between whether I duffed something up or I need to wait.

**Comment by will-in-wi** [comment]
The exit code for the app is 0 if success and non-0 in case of failure. This is because it is intended to be run by cron, which is usually set up to send an email to the administrator if there is any output from the command.

You could do something like `letsencrypt_webfaction [args…] && echo 'whatever you want to say'` if you want to.

However, per your request, I'm mulling over the idea of outputting some useful success text as you say, and adding a `-q` argument to eliminate that output for the cron usage… The downside of this is that it technically breaks existing workflows if someone blindly upgraded, so I'd have to increment the major version per semver. Or try to detect a pty, which might be error prone.

**Comment by radixdiaboli** [comment]
That makes sense.  Server admin is not really my thing, so newb misunderstanding on my part.

If you were to add a command, a --verbose option would avoid breaking workflows.

**Comment by will-in-wi** [comment]
It's a good suggestion overall. If I was starting over today, I'd do useful output and `-q` to silence it in cron. I'm just a little worried about breaking workflow. `--verbose` usually means more debugging output. Since the primary use case for this text would be people setting this up for the first time, I'm not sure they'd find the `--verbose` flag to give them that information…

I'll think about it and probably implement the help text and the `-q` flag. It's a really good idea. Thanks!

**Comment by will-in-wi** [comment]
https://github.com/will-in-wi/letsencrypt-webfaction/commit/766fcfd6c5498bcb836fae101d4e82645038bc6e provides this change, and is available in version 2.2.0.
