### ISSUE TITLE
Storing the certificates Webfaction

### ISSUE THREAD

**Issue by shermes641** [will-in-wi/letsencrypt-webfaction#92]
Just found your repo --- good stuff.

I am using NODEJS and doing a HTTPS - > HTTP proxy and need the cert, key and intermediate/bundle files in pem format for the httpproxy code.

Are these stored anywhere ?
Or can I get them from the Webfaction API ?

Thanks in advance

**Comment by will-in-wi** [comment]
The purpose of this library is to enable usage of the WebFaction edge servers as the TLS termination point. I'm not sure how your application is supposed to work in their environment…

The 1.x version of the library would download and store the various files including the chain on disk, and then send them an email. So if you disabled the email portion, it might do what you are looking for. Otherwise, I've seen tutorials to get acme.sh working on WebFaction, and that might be more useful for your usecase.

If you would like to provide more detail as to how your system is going to work, I might be able assist better. Usually, applications hit WebFaction's Nginx edge servers, SSL is terminated, and then unencrypted data is passed to the application server under your control. How is your application bypassing that and getting unterminated TLS from port 443?

**Comment by shermes641** [comment]
Thanks for your prompt reply.

I have a CouchDB served up on a custom port via http. The port is not exposed.
I have a static app being served from "/". I've assigned the cert to this website, and have a HTTPS -> HTTP proxy over to the CouchDB. The reason is that without root access setting up CouchDB for https is a bigger pain than this.

Before finding your app, I did get the acme.sh working, and it saves the files to disk.
I never used the email option (I'm not sure if webfaction even does the cert update via email anymore --- I'll have to ask). I just used the control panel to load the certs from the acme cert files, then tell my website to use them via the control panel.
I assumed your app saved the certs somewhere.

Here's my proxy code:

` exports.key_file = ' <path/to/key/file>';
exports.cert_file = '<path/to/cert/file>';
exports.start_proxy = function (key = this.key_file, cert = this.cert_file) {
    console.log('Starting HTTPS -> HTTP proxy  1234 -> 5678');
    httpProxy.createServer({
        target: {
            host: 'xxx.webfactional.com',
            port: 5678
        },
        ssl: {
            key: fs.readFileSync(key),
            cert: fs.readFileSync(cert)
        }
    }).listen(1234)`


Maybe I'm missing something in your procedure. I thought the cron job periodically issues new certs, and uses the webfaction api to automatically apply them to the appropriate websites.

If that is true, I think I can use the webfaction API to list the certs and save them to a file.
Then my app can pick them up.

Another thing I might be missing is: Does the acme script renew certs automatically ?
If it does I just have to add the steps to get them into webfaction.

Thanks again.
Namaste
steve

**Comment by will-in-wi** [comment]
I'm not sure about `acme.sh`, but `letsencrypt_webfaction` is designed to be run every two months (via cron) and issue a new certificate every time it is run. It pushes the certificate straight into the WebFaction API and does not store it anywhere else.

So, web -> WebFaction nginx server (443/https, passthrough) -> custom node app (443/https, terminated here) -> couchbase (custom port/http). Is that your intended flow?

If so, you might have better luck with an alternate flow: web -> WebFaction nginx server (443/https, terminated here) -> couchbase (custom port/http)/

You can accomplish this task by having the WebFaction Nginx edge servers terminate SSL for you. I tested this by using `php -S localhost:12345` as my CouchDB stand-in. I created a custom port application, and a website using it and a throwaway subdomain I created for this purpose. I configured the website to use https with the shared cert (for now). I also added my test subdomain to my existing https redirect application (runs on http and redirects everything sent to it to https). This was needed because issuing Let's Encrypt verifies apps on http, but follows redirects.

I then used letsencrypt_webfaction to create a certificate for this domain. I had created a folder called `~/test_custom_port/` and was running the above PHP server command in it (using a tmux session). The letsencrypt_webfaction command I ran was:

```bash
RBENV_ROOT=~/.rbenv RBENV_VERSION=2.3.1 ~/.rbenv/bin/rbenv exec letsencrypt_webfaction --domains porttest.example.com --public ~/test_custom_port/ --config ./le_config.yml --cert_name test_custom_port
```

This issued a certificate and installed it in the admin interface. I was then able to select it to be used by the custom port website. At this point, I had a website with valid https serving via 443 and proxying to my http app on a custom port.

In your case, you might want to create an http application on the same domain as your custom port but which doesn't redirect and serves the `.well-known` files for Let's Encrypt verification.

Does this make sense? Am I understanding your case correctly?

**Comment by shermes641** [comment]
You got it. I'll test this out for myself.
I need the nodejs app for several other purposes, so I added the proxy code to it.

Your solution is cleaner, and just to be clear, every time the certificate is renewed there is no need to do anything on webfaction. When your app creates the new certificates, the appropriate website is already configured to use them ?

Thanks so much for you time

Namaste
Steve

PS: I'll close this on your next reply

**Comment by will-in-wi** [comment]
Correct, when the cert is renewed, it replaces the existing certificate and thus requires no configuration change in the website.

Hope this works!

**Comment by shermes641** [comment]
I'll let you know, what could go wrong ? ;-)
